# Generated by Django 3.0.5 on 2020-04-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crwaling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
