# Generated by Django 3.0.5 on 2020-04-10 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crwaling', '0002_auto_20200410_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='pub_date',
        ),
    ]
