# Generated by Django 3.0.5 on 2020-04-12 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crwaling', '0003_remove_issue_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('problem_solve', models.IntegerField(default=0)),
                ('qeustion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crwaling.Issue')),
            ],
        ),
    ]
